/*
 * Copyright (c) 2026 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#include <dali-ui-foundation/dali-ui-foundation.h>
#include <dali-ui-test-suite-utils.h>
#include <dali.h>
#include <vector>

using namespace Dali;
using namespace Dali::Ui;

namespace
{
struct LayoutFinishedSignalData
{
  LayoutFinishedSignalData()
  : called(false),
    count(0)
  {
  }

  bool   called;
  int    count;
  Window window;
};

struct LayoutFinishedSignalFunctor
{
  LayoutFinishedSignalFunctor(LayoutFinishedSignalData& data)
  : signalData(data)
  {
  }

  void operator()(Window window)
  {
    signalData.called = true;
    ++signalData.count;
    signalData.window = window;
  }

  LayoutFinishedSignalData& signalData;
};

bool WasProcessEventsOnIdleRequested(UiTestApplication& application)
{
  return application.GetRenderController().WasCalled(TestRenderController::RequestProcessEventsOnIdleFunc);
}

// Consume a wake armed by event-time work. Clearing the harness flag before
// ProcessEvents makes any request observed afterwards attributable to work
// generated by that processing episode.
void SendRequestedProcessEvents(UiTestApplication& application)
{
  DALI_TEST_CHECK(WasProcessEventsOnIdleRequested(application));
  application.GetRenderController().Initialize();
  application.SendNotification();
}

// Model ProcessEvents being entered for a reason unrelated to layout. Retained
// PARK work must drain, but it must not use that opportunity to wake itself again.
void SendIndependentProcessEvents(UiTestApplication& application)
{
  application.GetRenderController().Initialize();
  application.SendNotification();
}

// Slot that removes the layout controller for its window from within the
// emit, exercising the deferred self-destruct path.
struct RemoveControllerInSlotFunctor
{
  RemoveControllerInSlotFunctor(int& count)
  : count(count)
  {
  }
  void operator()(Window window)
  {
    ++count;
    LayoutController::Remove(window);
  }
  int& count;
};

// ---- View::LayoutFinishedSignal test helpers ----
struct ViewLayoutFinishedSignalData
{
  ViewLayoutFinishedSignalData()
  : called(false),
    count(0),
    bounds(0.0f, 0.0f, 0.0f, 0.0f)
  {
  }
  bool       called;
  int        count;
  View       view;
  LayoutRect bounds;
};

struct ViewLayoutFinishedSignalFunctor
{
  explicit ViewLayoutFinishedSignalFunctor(ViewLayoutFinishedSignalData& data)
  : d(data)
  {
  }
  void operator()(View view, LayoutRect bounds)
  {
    d.called = true;
    ++d.count;
    d.view   = view;
    d.bounds = bounds;
  }
  ViewLayoutFinishedSignalData& d;
};

// Changes a layout PROPERTY on `target` once, on the first emit. The completed
// pass still emits its Window signal. This route and the public invalidation functor
// below fully retain another pass from inside the emit; neither may request an
// idle ProcessEvents wake from that processing episode.
struct ChangeWidthOnceFunctor
{
  ChangeWidthOnceFunctor(View target, int& count, bool& done)
  : target(target),
    count(count),
    done(done)
  {
  }
  void operator()(View, LayoutRect)
  {
    ++count;
    if(!done)
    {
      done = true;
      target.SetRequestedWidth(260.0f);
    }
  }
  View  target;
  int&  count;
  bool& done;
};

// Calls the PUBLIC View::InvalidateMeasure() from inside the emit, on every emit.
// The emit holds the layout processing window open, so the call is logged once,
// fully propagated, and parked without an idle wake. A separate event-time
// invalidation must still be able to upgrade this retained work to wakeable.
struct InvalidateFromSlotFunctor
{
  InvalidateFromSlotFunctor(View target, int& count)
  : target(target),
    count(count)
  {
  }
  void operator()(View, LayoutRect)
  {
    ++count;
    target.InvalidateMeasure();
  }
  View target;
  int& count;
};

// A measure producer that calls the PUBLIC LayoutController::RequestLayout() from
// inside its own view's measure pass. It inserts straight into the pending set,
// so the controller must apply the same retain-without-wake policy as it does to
// propagated View invalidation.
Window gRequestLayoutWindow;
View   gRequestLayoutTarget;
int    gRequestLayoutProducerCount = 0;

MeasuredSize RequestLayoutDuringMeasure(View, float, float)
{
  ++gRequestLayoutProducerCount;
  if(gRequestLayoutWindow && gRequestLayoutTarget)
  {
    LayoutController::Get(gRequestLayoutWindow).RequestLayout(&GetImpl(gRequestLayoutTarget));
  }
  return MeasuredSize(80.0f, 60.0f);
}

// On first emit, changes a layout property on `target` (a framework-internal
// invalidation subject to the same PARK policy) and RE-ENTERS ProcessLayouts
// explicitly. Both passes must retain their own completion snapshots.
struct ReenterProcessLayoutsFunctor
{
  ReenterProcessLayoutsFunctor(LayoutController& c, View target, int& count, bool& done)
  : controller(c),
    target(target),
    count(count),
    done(done)
  {
  }
  void operator()(View, LayoutRect)
  {
    ++count;
    if(!done)
    {
      done = true;
      target.SetRequestedWidth(120.0f);
      controller.ProcessLayouts();
    }
  }
  LayoutController& controller;
  View              target;
  int&              count;
  bool&             done;
};

// A View slot that removes the controller for `window`.
struct ViewSlotRemoveControllerFunctor
{
  ViewSlotRemoveControllerFunctor(Window window, int& count)
  : window(window),
    count(count)
  {
  }
  void operator()(View, LayoutRect)
  {
    ++count;
    LayoutController::Remove(window);
  }
  Window window;
  int&   count;
};

// Counts window layout-finished emits. Connected to a NEW controller created
// from inside another controller's emit.
struct CountLayoutFinishedFunctor
{
  explicit CountLayoutFinishedFunctor(int& count)
  : count(count)
  {
  }
  void operator()(Window)
  {
    ++count;
  }
  int& count;
};

// Slot that removes the controller for the emitting window and immediately
// re-obtains a NEW controller for the same window, connecting a counting slot
// to the new controller's signal. Exercises the idempotence of the deferred
// detach: the pass at the outermost Process unwind must leave the new
// controller alone.
struct RemoveThenGetInSlotFunctor
{
  RemoveThenGetInSlotFunctor(ConnectionTracker* tracker, int& count, int& newControllerCount)
  : tracker(tracker),
    count(count),
    newControllerCount(newControllerCount)
  {
  }
  void operator()(Window window)
  {
    ++count;
    LayoutController::Remove(window);
    LayoutController::Get(window).LayoutFinishedSignal().Connect(tracker, CountLayoutFinishedFunctor(newControllerCount));
  }
  ConnectionTracker* tracker;
  int&               count;
  int&               newControllerCount;
};
} // namespace

void utc_dali_layoutcontroller_startup(void)
{
  test_return_value = TET_UNDEF;
}

void utc_dali_layoutcontroller_cleanup(void)
{
  test_return_value = TET_PASS;
}

int UtcDaliLayoutControllerGetP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);
  controller.ProcessLayouts();
  DALI_TEST_CHECK(true);
  END_TEST;
}

int UtcDaliLayoutControllerOnWindowResizeP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);
  controller.OnWindowResize(320, 240);
  DALI_TEST_CHECK(true);
  END_TEST;
}

int UtcDaliLayoutControllerProcessLayoutsP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  // Add a view to the window so the controller has something to process.
  View view = View::New();
  view.SetRequestedWidth(100.0f);
  view.SetRequestedHeight(100.0f);
  window.Add(view);

  LayoutController& controller = LayoutController::Get(window);
  DALI_TEST_CHECK(WasProcessEventsOnIdleRequested(application));
  controller.ProcessLayouts();

  // ProcessLayouts() drained synchronously, but it did not consume the adaptor's
  // already-queued idle callback. Clear only the observation latch, then dirty
  // the view again: the controller must coalesce with that outstanding callback
  // instead of issuing a second RequestProcessEventsOnIdle.
  application.GetRenderController().Initialize();
  view.InvalidateMeasure();
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  // Model delivery of the original queued callback; it services the new work.
  application.SendNotification();
  application.Render();

  DALI_TEST_CHECK(true);
  END_TEST;
}

int UtcDaliLayoutControllerGetSameWindowReturnsSameInstanceP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& a = LayoutController::Get(window);
  LayoutController& b = LayoutController::Get(window);
  DALI_TEST_CHECK(&a == &b);
  END_TEST;
}

int UtcDaliLayoutControllerLayoutFinishedSignalP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);

  LayoutFinishedSignalData    data;
  LayoutFinishedSignalFunctor functor(data);
  controller.LayoutFinishedSignal().Connect(&application, functor);

  // Create a layout root under the window; this invalidates layout and queues
  // the root with the controller.
  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  // Drive a full pre+post cycle: the pre phase drains the pending work and the
  // post phase (after size negotiation) emits the signal exactly once.
  application.SendNotification();

  DALI_TEST_EQUALS(data.called, true, TEST_LOCATION);
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  DALI_TEST_CHECK(data.window == window);
  END_TEST;
}

int UtcDaliLayoutControllerLayoutFinishedSignalNoSpuriousEmitP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);

  LayoutFinishedSignalData    data;
  LayoutFinishedSignalFunctor functor(data);
  controller.LayoutFinishedSignal().Connect(&application, functor);

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);

  // Subsequent cycles with no completed pass must not create another event.
  application.SendNotification();
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerLayoutFinishedSignalRefiresP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);

  LayoutFinishedSignalData    data;
  LayoutFinishedSignalFunctor functor(data);
  controller.LayoutFinishedSignal().Connect(&application, functor);

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);

  // Invalidate again: the next completed pass fires the signal again.
  root.SetRequestedWidth(200.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 2, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerLayoutFinishedSignalRemoveInSlotP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  LayoutController& controller = LayoutController::Get(window);

  int                           removeCount = 0;
  RemoveControllerInSlotFunctor functor(removeCount);
  controller.LayoutFinishedSignal().Connect(&application, functor);

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  // The slot destroys the controller during the post-phase emit; the deferred
  // self-destruct (at the outermost Process unwind) must not cause a
  // use-after-free.
  application.SendNotification();
  DALI_TEST_EQUALS(removeCount, 1, TEST_LOCATION); // window signal fired exactly once before destroy
  // 'controller' is now dangling and must not be touched again.

  // A fresh Get() recreates the controller for the window without crashing.
  LayoutController& fresh = LayoutController::Get(window);
  (void)fresh;
  application.SendNotification();
  DALI_TEST_CHECK(true);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  View child = View::New();
  child.SetRequestedWidth(50.0f);
  child.SetRequestedHeight(40.0f);
  root.Add(child);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  child.LayoutFinishedSignal().Connect(&application, functor);

  // Drive a full pre+post cycle; the View signal emits in the post phase.
  application.SendNotification();

  DALI_TEST_EQUALS(data.called, true, TEST_LOCATION);
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  DALI_TEST_CHECK(data.view == child);
  Actor a = child;
  DALI_TEST_EQUALS(data.bounds.x, a.GetProperty<float>(Actor::Property::POSITION_X), 0.01f, TEST_LOCATION);
  DALI_TEST_EQUALS(data.bounds.y, a.GetProperty<float>(Actor::Property::POSITION_Y), 0.01f, TEST_LOCATION);
  DALI_TEST_EQUALS(data.bounds.width, a.GetProperty<float>(Actor::Property::SIZE_WIDTH), 0.01f, TEST_LOCATION);
  DALI_TEST_EQUALS(data.bounds.height, a.GetProperty<float>(Actor::Property::SIZE_HEIGHT), 0.01f, TEST_LOCATION);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalNoSpuriousEmitP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  root.LayoutFinishedSignal().Connect(&application, functor);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  application.SendNotification();
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalRefiresP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  root.LayoutFinishedSignal().Connect(&application, functor);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  root.SetRequestedWidth(240.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 2, TEST_LOCATION);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalSubscribedViewsOnlyP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  View childA = View::New();
  childA.SetRequestedWidth(50.0f);
  childA.SetRequestedHeight(40.0f);
  View childB = View::New();
  childB.SetRequestedWidth(60.0f);
  childB.SetRequestedHeight(30.0f);
  root.Add(childA);
  root.Add(childB);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  childA.LayoutFinishedSignal().Connect(&application, functor);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  DALI_TEST_CHECK(data.view == childA);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalRtlTargetBoundsP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  root.SetLayoutDirection(LayoutDirection::RIGHT_TO_LEFT);
  View child = View::New();
  child.SetRequestedWidth(50.0f);
  child.SetRequestedHeight(40.0f);
  root.Add(child);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  child.LayoutFinishedSignal().Connect(&application, functor);

  application.SendNotification();

  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  Actor a = child;
  DALI_TEST_EQUALS(data.bounds.x, a.GetProperty<float>(Actor::Property::POSITION_X), 0.01f, TEST_LOCATION);
  DALI_TEST_CHECK(data.bounds.x > 0.0f); // mirrored (LTR x would be 0)
  END_TEST;
}

// A View slot can leave another pass pending without cancelling the completed
// pass's Window signal. Scheduling remains parked until an independent event.
int UtcDaliViewLayoutFinishedSignalKeepsWindowSignalWhenSlotChangesPropertyP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  LayoutFinishedSignalData    winData;
  LayoutFinishedSignalFunctor winFunctor(winData);
  LayoutController&           controller = LayoutController::Get(window);
  controller.LayoutFinishedSignal().Connect(&application, winFunctor);

  int                    viewEmitCount = 0;
  bool                   didChange     = false;
  ChangeWidthOnceFunctor viewFunctor(root, viewEmitCount, didChange);
  root.LayoutFinishedSignal().Connect(&application, viewFunctor);

  // The View slot changes a property, but the Window signal still completes this
  // pass. The new calculation is retained without an idle wake.
  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(winData.count, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(viewEmitCount, 1, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  SendIndependentProcessEvents(application);
  DALI_TEST_EQUALS(winData.count, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(viewEmitCount, 2, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));
  END_TEST;
}

// A slot that unconditionally calls View::InvalidateMeasure() on every emit. The
// call is PARKED, never ignored: it is fully propagated and retained, but it does
// not cancel the completed pass's Window signal or wake another idle cycle.
// The second half also pins
// deferred->wakeable upgrade: a later event-time invalidation must reach the root
// and arm a wake even though an equivalent parked registration already exists.
int UtcDaliViewLayoutFinishedSlotInvalidationParkedN(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  LayoutFinishedSignalData    winData;
  LayoutFinishedSignalFunctor winFunctor(winData);
  LayoutController&           controller = LayoutController::Get(window);
  controller.LayoutFinishedSignal().Connect(&application, winFunctor);

  int                       viewEmitCount = 0;
  InvalidateFromSlotFunctor viewFunctor(root, viewEmitCount);
  root.LayoutFinishedSignal().Connect(&application, viewFunctor);

  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(viewEmitCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(winData.count, 1, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  // The slot left the root parked. An equivalent invalidation at event time must
  // upgrade that state and arm a real idle wake; generation/coalescing must not
  // swallow it merely because the parked walk recorded the same root earlier.
  root.InvalidateMeasure();
  DALI_TEST_CHECK(WasProcessEventsOnIdleRequested(application));

  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(viewEmitCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(winData.count, 2, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));
  END_TEST;
}

// The same PARK policy on the other public scheduling entry point. RequestLayout
// does not read a dirty bit; it retains the root directly. A request made by a
// measure producer must survive for the next ProcessEvents but must not arm it.
int UtcDaliLayoutControllerRequestLayoutDuringPassParkedN(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  tet_infoline("Public LayoutController::RequestLayout remains pending without an idle wake while a layout pass is on the stack");

  LayoutController&           controller = LayoutController::Get(window);
  LayoutFinishedSignalData    data;
  LayoutFinishedSignalFunctor functor(data);
  controller.LayoutFinishedSignal().Connect(&application, functor);

  gRequestLayoutProducerCount = 0;

  View view = View::New();
  view.SetRequestedWidth(200.0f);
  view.SetRequestedHeight(100.0f);
  view.SetMeasureCallback(MeasureCallback::New(&RequestLayoutDuringMeasure));

  gRequestLayoutWindow = window;
  gRequestLayoutTarget = view;

  window.Add(view);

  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(gRequestLayoutProducerCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  // The explicit trigger consumes the retained registration. Because RequestLayout
  // alone did not dirty the view, its measure cache hits and the producer does not
  // re-request. Its Arrange replay still completes another managed pass.
  SendIndependentProcessEvents(application);
  DALI_TEST_EQUALS(gRequestLayoutProducerCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(data.count, 2, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  gRequestLayoutTarget.Reset();
  gRequestLayoutWindow.Reset();
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalSlotReentersProcessLayoutsP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  View a = View::New();
  a.SetRequestedWidth(50.0f);
  a.SetRequestedHeight(40.0f);
  View b = View::New();
  b.SetRequestedWidth(60.0f);
  b.SetRequestedHeight(30.0f);
  root.Add(a);
  root.Add(b);
  window.Add(root);

  LayoutController&            controller = LayoutController::Get(window);
  std::vector<float>           widths;
  std::vector<int>             order;
  int                          aCount = 0;
  bool                         done   = false;
  ReenterProcessLayoutsFunctor reenter(controller, b, aCount, done);
  a.LayoutFinishedSignal().Connect(&application, [&](View view, LayoutRect bounds)
  {
    order.push_back(1);
    reenter(view, bounds);
  });
  b.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  {
    order.push_back(2);
    widths.push_back(bounds.width);
  });
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { order.push_back(3); });

  // A's callback completes a second pass synchronously. B must still receive its
  // original snapshot, followed by the original Window event in this post phase.
  application.SendNotification();
  DALI_TEST_EQUALS(aCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  DALI_TEST_CHECK(order == std::vector<int>({1, 2, 3}));
  if(widths.size() == 1u)
  {
    DALI_TEST_EQUALS(widths[0], 60.0f, 0.01f, TEST_LOCATION);
  }
  DALI_TEST_EQUALS(b.GetProperty<float>(Actor::Property::SIZE_WIDTH), 120.0f, 0.01f, TEST_LOCATION);

  // The nested pass must cross another pre/core-relayout/post boundary before
  // its separate snapshot is delivered. It may not replace the earlier event.
  application.SendNotification();
  DALI_TEST_EQUALS(aCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 2u, TEST_LOCATION);
  DALI_TEST_CHECK(order == std::vector<int>({1, 2, 3, 1, 2, 3}));
  if(widths.size() == 2u)
  {
    DALI_TEST_EQUALS(widths[1], 120.0f, 0.01f, TEST_LOCATION);
  }
  application.SendNotification();
  DALI_TEST_EQUALS(aCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 2u, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerManualPassesKeepSeparateSnapshotsP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  window.Add(root);
  LayoutController&  controller = LayoutController::Get(window);
  std::vector<float> widths;
  std::vector<int>   order;
  root.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  {
    widths.push_back(bounds.width);
    order.push_back(1);
  });
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { order.push_back(2); });

  controller.ProcessLayouts();
  root.SetRequestedWidth(180.0f);
  controller.ProcessLayouts();
  DALI_TEST_CHECK(widths.empty());
  DALI_TEST_CHECK(order.empty());
  DALI_TEST_EQUALS(root.GetProperty<float>(Actor::Property::SIZE_WIDTH), 180.0f, 0.01f, TEST_LOCATION);

  application.SendNotification();
  DALI_TEST_EQUALS(widths.size(), 2u, TEST_LOCATION);
  DALI_TEST_CHECK(order == std::vector<int>({1, 2, 1, 2}));
  if(widths.size() == 2u)
  {
    DALI_TEST_EQUALS(widths[0], 100.0f, 0.01f, TEST_LOCATION);
    DALI_TEST_EQUALS(widths[1], 180.0f, 0.01f, TEST_LOCATION);
  }
  application.SendNotification();
  DALI_TEST_EQUALS(widths.size(), 2u, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerCrossWindowPostRequiresNewBoundaryP(void)
{
  UiTestApplication application;
  Window            first            = application.GetWindow();
  LayoutController& firstController  = LayoutController::Get(first);
  Window            second           = Window::New(PositionSize(0, 0, 320, 240), "layout-pass-second");
  LayoutController& secondController = LayoutController::Get(second);
  View              source           = View::New();
  source.SetRequestedWidth(100.0f);
  source.SetRequestedHeight(60.0f);
  View target = View::New();
  target.SetRequestedWidth(80.0f);
  target.SetRequestedHeight(50.0f);
  first.Add(source);
  second.Add(target);

  std::vector<float> widths;
  int                firstCount  = 0;
  int                secondCount = 0;
  target.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  { widths.push_back(bounds.width); });
  firstController.LayoutFinishedSignal().Connect(&application, [&](Window)
  {
    ++firstCount;
    target.SetRequestedWidth(160.0f);
    secondController.ProcessLayouts();
  });
  secondController.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++secondCount; });

  // First's post callback calculates a NEW second-window pass after core Relayout.
  // Second's later post callback may emit only the pass eligible at its pre phase.
  application.SendNotification();
  DALI_TEST_EQUALS(firstCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(secondCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  if(widths.size() == 1u)
  {
    DALI_TEST_EQUALS(widths[0], 80.0f, 0.01f, TEST_LOCATION);
  }
  DALI_TEST_EQUALS(target.GetProperty<float>(Actor::Property::SIZE_WIDTH), 160.0f, 0.01f, TEST_LOCATION);

  application.SendNotification();
  DALI_TEST_EQUALS(firstCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(secondCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 2u, TEST_LOCATION);
  if(widths.size() == 2u)
  {
    DALI_TEST_EQUALS(widths[1], 160.0f, 0.01f, TEST_LOCATION);
  }
  LayoutController::Remove(second);
  application.RunIdles();
  END_TEST;
}

int UtcDaliLayoutControllerRemovedPendingRootDoesNotFinishP(void)
{
  UiTestApplication application;
  Window            window     = application.GetWindow();
  LayoutController& controller = LayoutController::Get(window);
  int               finishes   = 0;
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++finishes; });
  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  window.Add(root);
  window.Remove(root);
  root.Reset();

  // A dirty registration whose root died never completed a pass.
  controller.ProcessLayouts();
  application.SendNotification();
  DALI_TEST_EQUALS(finishes, 0, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerRemoveStopsRemainingPassEventsP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  window.Add(root);
  LayoutController& controller = LayoutController::Get(window);
  int               views      = 0;
  int               windows    = 0;
  root.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect)
  { ++views; });
  controller.LayoutFinishedSignal().Connect(&application, [&](Window emittedWindow)
  {
    ++windows;
    LayoutController::Remove(emittedWindow);
  });
  controller.ProcessLayouts();
  root.SetRequestedWidth(180.0f);
  controller.ProcessLayouts();
  application.SendNotification();
  DALI_TEST_EQUALS(views, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(windows, 1, TEST_LOCATION);
  application.RunIdles();
  END_TEST;
}

int UtcDaliLayoutControllerRemoveInViewStopsCurrentCohortP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  View first = View::New();
  first.SetRequestedWidth(40.0f);
  first.SetRequestedHeight(30.0f);
  View second = View::New();
  second.SetRequestedWidth(50.0f);
  second.SetRequestedHeight(30.0f);
  root.Add(first);
  root.Add(second);
  window.Add(root);
  int firstCount  = 0;
  int secondCount = 0;
  int windowCount = 0;
  first.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect)
  {
    ++firstCount;
    LayoutController::Remove(window);
  });
  second.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect)
  { ++secondCount; });
  LayoutController::Get(window).LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++windowCount; });
  application.SendNotification();
  DALI_TEST_EQUALS(firstCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(secondCount, 0, TEST_LOCATION);
  DALI_TEST_EQUALS(windowCount, 0, TEST_LOCATION);
  application.RunIdles();
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalRemoveViewBeforeEmitP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  View child = View::New();
  child.SetRequestedWidth(50.0f);
  child.SetRequestedHeight(40.0f);
  root.Add(child);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  child.LayoutFinishedSignal().Connect(&application, functor);

  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);

  root.Remove(child);
  int before = data.count;
  root.SetRequestedWidth(240.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, before, TEST_LOCATION); // no emit for removed child, no UAF
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalManualArrangeNoOpP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  ViewLayoutFinishedSignalData    data;
  ViewLayoutFinishedSignalFunctor functor(data);
  root.LayoutFinishedSignal().Connect(&application, functor);

  GetImpl(root).Arrange(LayoutRect(0.0f, 0.0f, 100.0f, 100.0f)); // no active pass
  DALI_TEST_EQUALS(data.called, false, TEST_LOCATION);
  END_TEST;
}

int UtcDaliViewLayoutFinishedSignalRemoveControllerInSlotP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  View              root   = View::New();
  root.SetRequestedWidth(200.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  int                             slotCount = 0;
  ViewSlotRemoveControllerFunctor functor(window, slotCount);
  root.LayoutFinishedSignal().Connect(&application, functor);

  // The View slot destroys the controller during the post-phase View emit; the
  // deferred self-destruct at the outermost Process unwind must be UAF-safe.
  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(slotCount, 1, TEST_LOCATION);

  LayoutController& fresh = LayoutController::Get(window);
  (void)fresh;
  application.SendNotification();
  DALI_TEST_CHECK(true);
  END_TEST;
}

int UtcDaliLayoutControllerRemoveThenGetInSlotP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  int                        slotCount          = 0;
  int                        newControllerCount = 0;
  RemoveThenGetInSlotFunctor functor(&application, slotCount, newControllerCount);
  LayoutController::Get(window).LayoutFinishedSignal().Connect(&application, functor);

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  // The slot removes the controller and creates a NEW one for the same window
  // during the emit. The deferred detach that runs when the old controller's
  // Process frame unwinds is idempotent and must NOT queue the new controller
  // for the deferred free.
  application.SendNotification();
  DALI_TEST_EQUALS(slotCount, 1, TEST_LOCATION);

  // Drain the deferred free; only the OLD controller may be freed here.
  application.RunIdles();

  // The new controller must be alive and functional: a fresh layout pass has
  // to emit through the slot connected from inside the removal slot. This also
  // pins generation teardown: detaching the old controller discarded its
  // registrations, so the same View's event-time invalidation must walk to the
  // new controller and arm a fresh idle wake.
  root.SetRequestedWidth(150.0f);
  DALI_TEST_CHECK(WasProcessEventsOnIdleRequested(application));
  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(newControllerCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(slotCount, 1, TEST_LOCATION); // detached controller stays silent
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));
  END_TEST;
}

int UtcDaliLayoutControllerRemoveInSlotIdleReapP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();

  int                           removeCount = 0;
  RemoveControllerInSlotFunctor functor(removeCount);
  LayoutController::Get(window).LayoutFinishedSignal().Connect(&application, functor);

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(100.0f);
  window.Add(root);

  // The slot detaches the controller during the emit; the free is queued for
  // the idle callback.
  application.SendNotification();
  DALI_TEST_EQUALS(removeCount, 1, TEST_LOCATION);

  // Idle runs the deferred free of the detached controller. Must not crash.
  application.RunIdles();

  // A fresh controller works end-to-end after the reap.
  LayoutFinishedSignalData    data;
  LayoutFinishedSignalFunctor freshFunctor(data);
  LayoutController::Get(window).LayoutFinishedSignal().Connect(&application, freshFunctor);
  root.SetRequestedWidth(180.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(data.called, true, TEST_LOCATION);
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);

  // Removing from ordinary (non-slot) code also frees only at idle; afterwards
  // the freed controller's signal is gone and a third controller takes over
  // without re-firing the old slot.
  LayoutController::Remove(window);
  application.RunIdles();

  root.SetRequestedWidth(120.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(data.count, 1, TEST_LOCATION);
  END_TEST;
}

namespace
{
// Records the constraint the producer was run at, so a test can assert the UNIT of that
// constraint and not merely the size that came out of it.
float gRecordedMeasureWidthConstraint  = -1.0f;
float gRecordedMeasureHeightConstraint = -1.0f;

MeasuredSize RecordMeasureConstraint(View, float widthConstraint, float heightConstraint)
{
  gRecordedMeasureWidthConstraint  = widthConstraint;
  gRecordedMeasureHeightConstraint = heightConstraint;
  return MeasuredSize(200.0f, 160.0f);
}
} // namespace

// A layout root's requested size is stored in NATURAL units while every constraint the
// layout pass carries is VISUAL, so the controller must scale it. The other two sources
// of a root constraint -- the window size and the parent actor SIZE -- are visual
// already, and so is the parameter Measure() takes, so a root measured at its raw
// requested size is run at a constraint 1/s too small.
//
// UiScaleManagerImpl keeps the scale in a process-wide singleton, so the incoming scale
// is recorded and restored.
//
// Non-vacuity (verified by mutation): dropping the * scale from the FIXED width branch
// of ProcessLayoutRoot makes the recorded width constraint 100 instead of 200.
int UtcDaliLayoutControllerFixedRootMeasuredAtVisualConstraintP(void)
{
  UiTestApplication application;
  tet_infoline("A FIXED-size layout root is measured at a VISUAL constraint");

  const float originalScale = UiScaleManager::Get().GetScale();
  UiScaleManager::Get().SetScale(2.0f);

  gRecordedMeasureWidthConstraint  = -1.0f;
  gRecordedMeasureHeightConstraint = -1.0f;

  Window window = application.GetWindow();

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(80.0f);
  root.SetMeasureCallback(MeasureCallback::New(&RecordMeasureConstraint));
  window.Add(root);

  application.SendNotification();
  application.Render();

  // Exact, not epsilon: the value under test is a factor of the scale apart from the
  // wrong one, and an epsilon compare here would only weaken the assertion.
  DALI_TEST_EQUALS(gRecordedMeasureWidthConstraint, 200.0f, TEST_LOCATION);
  DALI_TEST_EQUALS(gRecordedMeasureHeightConstraint, 160.0f, TEST_LOCATION);
  DALI_TEST_EQUALS(root.GetProperty<float>(Actor::Property::SIZE_WIDTH), 200.0f, TEST_LOCATION);

  UiScaleManager::Get().SetScale(originalScale);
  END_TEST;
}

// The same root at the unit scale, where natural and visual units coincide: the
// conversion must be a no-op there, or every existing app would see a changed
// constraint.
int UtcDaliLayoutControllerFixedRootConstraintUnchangedAtUnitScaleP(void)
{
  UiTestApplication application;
  tet_infoline("A FIXED-size layout root sees its requested size unchanged at scale 1");

  const float originalScale = UiScaleManager::Get().GetScale();
  UiScaleManager::Get().SetScale(1.0f);

  gRecordedMeasureWidthConstraint  = -1.0f;
  gRecordedMeasureHeightConstraint = -1.0f;

  Window window = application.GetWindow();

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(80.0f);
  root.SetMeasureCallback(MeasureCallback::New(&RecordMeasureConstraint));
  window.Add(root);

  application.SendNotification();
  application.Render();

  DALI_TEST_EQUALS(gRecordedMeasureWidthConstraint, 100.0f, TEST_LOCATION);
  DALI_TEST_EQUALS(gRecordedMeasureHeightConstraint, 80.0f, TEST_LOCATION);

  UiScaleManager::Get().SetScale(originalScale);
  END_TEST;
}

// The end-to-end geometry of the same shape at a non-unit scale: a FIXED root with a
// WRAP_CONTENT boundary child that wraps a 90 wide grandchild. Every extent on the path
// (the root's own visual size, the extent the boundary child is handed, and the child's
// wrapped content) is in visual units, so the child settles at 90 * 2.
//
// Unlike the two tests above this one does NOT discriminate the FIXED-branch conversion,
// and deliberately so: it is the geometry regression guard for the shape the conversion
// touches. A FIXED root's own size comes from its requested size rather than from the
// constraint, and a boundary child is re-measured by its own root pass from the parent's
// (already visual) actor SIZE, so the constraint the root's producer is run at -- what the
// two tests above assert directly -- is not observable in the settled geometry here.
int UtcDaliLayoutControllerFixedRootStandaloneChildGetsFullExtentP(void)
{
  UiTestApplication application;
  tet_infoline("A FIXED-size root hands its boundary child the full visual extent");

  const float originalScale = UiScaleManager::Get().GetScale();
  UiScaleManager::Get().SetScale(2.0f);

  Window window = application.GetWindow();

  View root = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(80.0f);
  window.Add(root);

  View standalone = View::New();
  standalone.SetLayoutMode(LayoutMode::STANDALONE);
  standalone.SetRequestedWidth(WRAP_CONTENT);
  standalone.SetMaximumWidth(1000.0f);
  root.Add(standalone);

  View grandChild = View::New();
  grandChild.SetRequestedWidth(90.0f);
  standalone.Add(grandChild);

  application.SendNotification();
  application.Render();

  // 90 natural content at scale 2, and a boundary child that wraps it.
  DALI_TEST_EQUALS(standalone.GetProperty<float>(Actor::Property::SIZE_WIDTH), 180.0f, TEST_LOCATION);

  UiScaleManager::Get().SetScale(originalScale);
  END_TEST;
}

// ─── Exception safety of one processing batch ─────────────────────────────
//
// Placed LAST in this file on purpose: it deliberately unwinds a Dali::DaliException
// out of a layout pass. The pass is driven through the MANUAL entry point
// (LayoutController::ProcessLayouts) rather than SendNotification, because
// Core::ProcessEvents sets its re-entrancy latch without RAII: an exception escaping it
// would leave that Core refusing every later ProcessEvents call, and the retry this test
// has to observe could never run.
namespace
{
int  gThrowingMeasureCount = 0;
int  gExceptionTargetCount = 0;
bool gThrowingMeasureArmed = false;

// Throws once, and only while armed. DALI_ASSERT_ALWAYS raises exactly this type, so
// this stands in for any assertion firing inside a producer.
MeasuredSize ThrowWhenArmedMeasure(View, float, float)
{
  ++gThrowingMeasureCount;
  if(gThrowingMeasureArmed)
  {
    gThrowingMeasureArmed = false;
    throw Dali::DaliException("utc", "injected");
  }
  return MeasuredSize(200.0f, 100.0f);
}

MeasuredSize ExceptionTargetMeasure(View, float, float)
{
  ++gExceptionTargetCount;
  return MeasuredSize(100.0f, 50.0f);
}

// Arms the throw and re-dirties both roots from inside the LayoutFinished emit, exactly
// once. Invalidating from a slot is PARKED: the work lands in the pending set but arms no
// idle wake, which is what leaves mIdleWakeArmed false and makes the no-wake assertion
// below observable rather than vacuous.
struct ArmThrowAndInvalidateOnce
{
  ArmThrowAndInvalidateOnce(int& count, View source, View target)
  : count(count),
    source(source),
    target(target)
  {
  }
  void operator()(Window)
  {
    ++count;
    if(count == 1)
    {
      gThrowingMeasureArmed = true;
      source.InvalidateMeasure();
      target.InvalidateMeasure();
    }
  }
  int& count;
  View source;
  View target;
};
} // namespace

// ProcessLayouts swaps the pending set into a stack-local vector, so between the swap
// and the end of the loop the member set names NONE of the roots still to run. An
// exception out of a producer destroys that vector and used to lose them all: the
// second root's layout would simply never run again, and nothing would re-register it.
//
// Non-vacuity (verified by mutation): disarming PendingBatchRollbackScope leaves the
// target's producer count frozen and the source is never retried either.
int UtcDaliLayoutControllerBatchSurvivesProducerExceptionP(void)
{
  UiTestApplication application;
  Window            window = application.GetWindow();
  tet_infoline("A producer exception does not lose the rest of the pending batch");

  gThrowingMeasureCount = 0;
  gExceptionTargetCount = 0;
  gThrowingMeasureArmed = false;

  // Directly under the Window (depth 1), so the depth sort runs it FIRST.
  View source = View::New();
  source.SetRequestedWidth(200.0f);
  source.SetRequestedHeight(100.0f);
  source.SetMeasureCallback(MeasureCallback::New(&ThrowWhenArmedMeasure));

  // Under a non-View actor (depth 2): an independent layout root that the sort places
  // after `source`, so it is still queued when `source` throws.
  Actor targetHost = Actor::New();
  View  target     = View::New();
  target.SetRequestedWidth(100.0f);
  target.SetRequestedHeight(50.0f);
  target.SetMeasureCallback(MeasureCallback::New(&ExceptionTargetMeasure));

  int                       emitCount = 0;
  ArmThrowAndInvalidateOnce rearm(emitCount, source, target);
  LayoutController::Get(window).LayoutFinishedSignal().Connect(&application, rearm);

  window.Add(source);
  window.Add(targetHost);
  targetHost.Add(target);

  // A normal batch first. It completes, emits once, and the slot then arms the throw and
  // parks a fresh dirty state on both roots without requesting a wake.
  SendRequestedProcessEvents(application);
  DALI_TEST_EQUALS(emitCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(gThrowingMeasureCount, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(gExceptionTargetCount, 1, TEST_LOCATION);
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));

  // 1. The parked batch runs and the FIRST root's producer throws out of it.
  bool caught = false;
  try
  {
    LayoutController::Get(window).ProcessLayouts();
  }
  catch(const Dali::DaliException&)
  {
    caught = true;
  }
  DALI_TEST_CHECK(caught);
  DALI_TEST_EQUALS(gThrowingMeasureCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(gExceptionTargetCount, 1, TEST_LOCATION); // never got its turn

  // 2. The rollback re-registered both roots WITHOUT arming an idle wake: a wake here
  //    would re-drive the producer that just threw, at full main-loop rate. No wake was
  //    outstanding going in, so this really does observe the rollback's own choice.
  DALI_TEST_CHECK(!WasProcessEventsOnIdleRequested(application));
  DALI_TEST_EQUALS(emitCount, 1, TEST_LOCATION);

  // 3. The next independently driven cycle drains the restored batch. The target runs
  //    for the first time since the abort, and the source retries.
  SendIndependentProcessEvents(application);
  DALI_TEST_EQUALS(gExceptionTargetCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(gThrowingMeasureCount, 3, TEST_LOCATION);

  // 4. The successful retry produces another pass completion event.
  DALI_TEST_EQUALS(emitCount, 2, TEST_LOCATION);

  // Steady state: nothing re-schedules itself.
  SendIndependentProcessEvents(application);
  DALI_TEST_EQUALS(gExceptionTargetCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(gThrowingMeasureCount, 3, TEST_LOCATION);
  DALI_TEST_EQUALS(emitCount, 2, TEST_LOCATION);

  END_TEST;
}

// Catch producer failures through the manual entry point so Core::ProcessEvents'
// non-RAII reentrancy latch is not left set by the injected exception.
int UtcDaliLayoutControllerFailedBatchDropsPartialCompletionP(void)
{
  UiTestApplication application;
  Window            window     = application.GetWindow();
  LayoutController& controller = LayoutController::Get(window);
  gThrowingMeasureCount        = 0;
  gThrowingMeasureArmed        = false;

  View first = View::New();
  first.SetRequestedWidth(100.0f);
  first.SetRequestedHeight(60.0f);
  Actor host     = Actor::New();
  View  throwing = View::New();
  throwing.SetRequestedWidth(80.0f);
  throwing.SetRequestedHeight(50.0f);
  throwing.SetMeasureCallback(MeasureCallback::New(&ThrowWhenArmedMeasure));
  window.Add(first);
  window.Add(host);
  host.Add(throwing);

  std::vector<float> widths;
  int                finishes = 0;
  first.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  { widths.push_back(bounds.width); });
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++finishes; });

  // Keep the first successful batch queued without delivering it yet.
  controller.ProcessLayouts();
  DALI_TEST_EQUALS(gThrowingMeasureCount, 1, TEST_LOCATION);
  first.SetRequestedWidth(140.0f);
  throwing.InvalidateMeasure();
  gThrowingMeasureArmed = true;
  bool caught           = false;
  try
  {
    // The shallower root produces a width-140 snapshot before the later root throws.
    controller.ProcessLayouts();
  }
  catch(const Dali::DaliException&)
  {
    caught = true;
  }
  DALI_TEST_CHECK(caught);
  DALI_TEST_EQUALS(gThrowingMeasureCount, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(first.GetProperty<float>(Actor::Property::SIZE_WIDTH), 140.0f, 0.01f, TEST_LOCATION);
  DALI_TEST_CHECK(widths.empty());
  DALI_TEST_EQUALS(finishes, 0, TEST_LOCATION);

  // Remove the failed root so the next pre phase cannot manufacture a successful
  // retry that would hide an erroneous partial completion record.
  host.Remove(throwing);
  throwing.Reset();
  window.Remove(host);
  host.Reset();
  application.SendNotification();
  DALI_TEST_EQUALS(finishes, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  if(widths.size() == 1u)
  {
    DALI_TEST_EQUALS(widths[0], 100.0f, 0.01f, TEST_LOCATION);
  }
  application.SendNotification();
  DALI_TEST_EQUALS(finishes, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerLateConnectionDoesNotReplayPassP(void)
{
  UiTestApplication application;
  Window            window     = application.GetWindow();
  LayoutController& controller = LayoutController::Get(window);
  View              root       = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  window.Add(root);
  int views   = 0;
  int windows = 0;
  root.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect)
  { ++views; });
  controller.ProcessLayouts();
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++windows; });
  application.SendNotification();
  DALI_TEST_EQUALS(views, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(windows, 0, TEST_LOCATION);

  root.SetRequestedWidth(120.0f);
  application.SendNotification();
  DALI_TEST_EQUALS(views, 2, TEST_LOCATION);
  DALI_TEST_EQUALS(windows, 1, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerOffsceneViewCancelsQueuedSnapshotP(void)
{
  UiTestApplication application;
  Window            window     = application.GetWindow();
  LayoutController& controller = LayoutController::Get(window);
  View              root       = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  window.Add(root);
  std::vector<float> widths;
  int                windows = 0;
  root.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  { widths.push_back(bounds.width); });
  controller.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++windows; });
  controller.ProcessLayouts();
  window.Remove(root);
  DALI_TEST_CHECK(root); // Keep the handle alive: expiration alone cannot cancel it.
  application.SendNotification();
  DALI_TEST_CHECK(widths.empty());
  DALI_TEST_EQUALS(windows, 1, TEST_LOCATION);

  root.SetRequestedWidth(180.0f);
  window.Add(root);
  application.SendNotification();
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  if(widths.size() == 1u)
  {
    DALI_TEST_EQUALS(widths[0], 180.0f, 0.01f, TEST_LOCATION);
  }
  DALI_TEST_EQUALS(windows, 2, TEST_LOCATION);
  END_TEST;
}

int UtcDaliLayoutControllerReparentCancelsPreviousWindowSnapshotP(void)
{
  UiTestApplication application;
  Window            first            = application.GetWindow();
  LayoutController& firstController  = LayoutController::Get(first);
  Window            second           = Window::New(PositionSize(0, 0, 320, 240), "layout-pass-reparent");
  LayoutController& secondController = LayoutController::Get(second);
  View              root             = View::New();
  root.SetRequestedWidth(100.0f);
  root.SetRequestedHeight(60.0f);
  first.Add(root);
  std::vector<float> widths;
  int                firstWindows  = 0;
  int                secondWindows = 0;
  root.LayoutFinishedSignal().Connect(&application, [&](View, LayoutRect bounds)
  { widths.push_back(bounds.width); });
  firstController.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++firstWindows; });
  secondController.LayoutFinishedSignal().Connect(&application, [&](Window)
  { ++secondWindows; });
  firstController.ProcessLayouts();

  // The same live View moves to another window before its old snapshot is emitted.
  first.Remove(root);
  second.Add(root);
  root.SetRequestedWidth(220.0f);
  secondController.ProcessLayouts();
  application.SendNotification();
  DALI_TEST_EQUALS(firstWindows, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(secondWindows, 1, TEST_LOCATION);
  DALI_TEST_EQUALS(widths.size(), 1u, TEST_LOCATION);
  if(widths.size() == 1u)
  {
    DALI_TEST_EQUALS(widths[0], 220.0f, 0.01f, TEST_LOCATION);
  }
  LayoutController::Remove(second);
  application.RunIdles();
  END_TEST;
}
